import './style.css';
import './hero-image.css';

type Check = { label: string; detail: string; state: 'ready' | 'risk' | 'missing' | 'done' };
type Draft = { title:string; owner:string; changed:string[]; checks:Check[]; source:string };
const sample: Draft = {
  title: 'Add organization-level retention controls', owner: 'Mira Chen', source: 'PR #482 · agent-authored',
  changed: ['src/policy/retention.ts', 'db/migrations/20260828_retention.sql', 'src/api/export.ts'],
  checks: [
    {label:'Contract changed',detail:'Export API now returns retention state.',state:'ready'},
    {label:'Migration found',detail:'Adds retention_days and backfills 14,382 rows.',state:'risk'},
    {label:'Test evidence',detail:'pnpm test: 214 passed · migration check: passed',state:'ready'},
    {label:'Risky path',detail:'db/migrations requires database owner sign-off.',state:'risk'}
  ]
};
let demo = location.pathname === '/demo' || new URLSearchParams(location.search).get('demo') === '1';
let draft: Draft | null = demo ? structuredClone(sample) : null;
let offline = !navigator.onLine;
const app = document.querySelector<HTMLDivElement>('#app')!;
const esc = (s:string) => s.replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const nav = (path:string) => { history.pushState({},'',path); render(); };

function shell(content:string, page:string, title:string) {
  document.title=title;
  app.innerHTML=`<a class="skip" href="#main">Skip to content</a><header class="site-head"><a class="wordmark" href="/" data-nav><span class="mark" aria-hidden="true">≡</span> Diff Gate</a><nav aria-label="Main navigation"><a href="/demo" data-nav>Demo</a><a href="/#how">How it works</a><a href="/privacy" data-nav>Privacy</a></nav></header>${demo?`<aside class="demo-bar" aria-label="Demo mode"><span><b>Demo</b> — sample data, nothing is saved</span><span><button class="text-button" id="reset-demo">Reset demo</button><button class="text-button" id="start-real">Start for real</button></span></aside>`:''}<p id="announcer" class="sr-only" aria-live="polite">${page}</p><main id="main" tabindex="-1">${content}</main><footer><span>Diff Gate makes change ownership visible.</span><span><a href="/privacy" data-nav>Privacy</a> <a href="/terms" data-nav>Terms</a> <a href="https://paramfactory.com" rel="external">Built by Param Factory</a></span><small>v0.1.0</small></footer>`;
  bind(); requestAnimationFrame(()=>document.querySelector<HTMLElement>('h1')?.focus({preventScroll:true}));
}
function packetUI() {
  if(!draft) return `<section class="empty-panel" aria-labelledby="empty-title"><p class="eyebrow">Your review desk</p><h2 id="empty-title">Start a review packet</h2><p>A packet collects the owner, changed contracts, test proof, and paths that need attention.</p><div class="button-row"><button class="primary" id="load-sample">Try it with sample data</button><button class="secondary" id="make-packet">Create a blank packet</button></div>${offline?'<p class="status warning" role="status">You are offline. Load sample data or reconnect to save a packet.</p>':''}</section>`;
  const blockers=draft.checks.filter(c=>c.state==='risk'||c.state==='missing').length;
  return `<section class="packet" aria-labelledby="packet-title"><div class="packet-head"><div><p class="eyebrow">${esc(draft.source)}</p><h2 id="packet-title">${esc(draft.title)}</h2><p class="packet-meta">Accountable owner: <strong>${esc(draft.owner)}</strong></p></div><div class="stamp ${blockers?'hold':'approved'}" aria-label="${blockers?'Review hold':'Ready to approve'}"><span>${blockers?'HOLD':'READY'}</span><small>${blockers?`${blockers} owner check${blockers===1?'':'s'}`:'evidence attached'}</small></div></div><div class="packet-grid"><section aria-labelledby="changed-title"><h3 id="changed-title">Changed files</h3><ul class="file-list">${draft.changed.map((f,i)=>`<li><span class="file-no">0${i+1}</span><code>${esc(f)}</code></li>`).join('')}</ul></section><section aria-labelledby="checks-title"><h3 id="checks-title">Review evidence</h3><ul class="checks">${draft.checks.map((c,i)=>`<li class="check ${c.state}"><span class="state-dot" aria-hidden="true">${c.state==='risk'?'!':c.state==='done'?'✓':'•'}</span><div><strong>${esc(c.label)}</strong><p>${esc(c.detail)}</p></div>${c.state==='risk'?`<button class="small-button" data-resolve="${i}">Mark reviewed</button>`:''}</li>`).join('')}</ul></section></div><div class="packet-actions"><button class="secondary" id="export-packet">Export packet</button><button class="primary" id="approve-packet" ${blockers?'disabled aria-describedby="approval-note"':''}>Approve for merge</button><p id="approval-note" class="status ${blockers?'warning':'success'}" role="status">${blockers?'Resolve each flagged owner check before approval.':'All flagged checks are reviewed. Approval records the owner and evidence.'}</p></div></section>`;
}
function landing() {
  queueMicrotask(() => { const hero = document.querySelector('.hero-print'); if (hero) hero.innerHTML = '<img src="/change-control.webp" width="900" height="600" fetchpriority="high" decoding="async" alt="Printed file sheets and review marks arranged across a change-control desk."><b class="art-stamp">CHECK</b>'; });
  shell(`<section class="hero"><div class="hero-copy"><p class="eyebrow">Accountable review for agent changes</p><h1 tabindex="-1">Review agent changes before merge</h1><p class="lede">For small software teams who need an owner and evidence before an agent-made change lands.</p><div class="button-row"><button class="primary" id="hero-demo">Try it with sample data</button><span class="after-action">Opens a complete review packet.</span></div><ul class="facts"><li>Sample data stays in this browser.</li><li>No GitHub install needed to try it.</li><li>$99 per team each month when connected.</li></ul></div><figure class="hero-art"><div class="hero-print" role="img" aria-label="Printed file sheets, a test receipt, and an approval stamp arranged as a review desk."><i class="paper p1"></i><i class="paper p2"></i><i class="receipt"></i><b class="art-stamp">CHECK</b></div><figcaption>Every change gets an owner, evidence, and a clear review state.</figcaption></figure></section><section class="live-area" aria-labelledby="desk-title"><div class="section-kicker"><p class="eyebrow">Live review desk</p><h2 id="desk-title">Find the merge blockers first</h2></div>${packetUI()}</section><section id="how" class="how" aria-labelledby="how-title"><p class="eyebrow">How it works</p><h2 id="how-title">Make the review decision visible</h2><ol><li><b>Open a packet.</b><span>Start with a PR or a sample packet.</span></li><li><b>Check the evidence.</b><span>See contracts, migrations, tests, and risky paths together.</span></li><li><b>Name the owner.</b><span>Record who can approve the change before merge.</span></li></ol></section><section class="boundary" aria-labelledby="boundary-title"><h2 id="boundary-title">It does not merge code for you</h2><p>Diff Gate keeps security findings advisory. Your team decides what to change and who approves it.</p><p>Repository code is not used to train this product.</p></section><section class="pricing" aria-labelledby="pricing-title"><p class="eyebrow">Team plan</p><h2 id="pricing-title">Connect your team for $99 per month</h2><p>Connect GitHub review packets, retained audit history, and owner rules. Checkout is handled by Sociobot.</p><a class="primary link-button" href="https://api.sociobot.in/api/v1/products/agent-diff-gate/checkout">Buy team access</a><details><summary>Have a license? Paste it</summary><label for="license">License token</label><div class="license-row"><input id="license" autocomplete="off"><button class="secondary" id="save-license">Restore access</button></div><p id="license-note" role="status"></p></details></section>`, 'Diff Gate home', 'Diff Gate — Review agent changes before merge');
}
function demoPage() { shell(`<section class="app-page"><div class="section-kicker"><p class="eyebrow">Sample review packet</p><h1 tabindex="-1">See an agent change under review</h1><p class="lede">Inspect the owner, evidence, and risky paths. This sample is separate from real packets.</p></div>${packetUI()}</section>`, 'Demo — Diff Gate', 'Demo — Diff Gate'); }
function legal(kind:'privacy'|'terms') { const privacy=kind==='privacy'; shell(`<article class="legal"><p class="eyebrow">Diff Gate ${privacy?'privacy':'terms'}</p><h1 tabindex="-1">${privacy?'Your review data stays in your control':'Terms for using Diff Gate'}</h1>${privacy?'<p>Demo data stays in the demo browser storage and is discarded when you leave demo mode.</p><p>Saved packets contain only the title, named owner, and evidence that you submit. We do not use repository code to train models.</p><p>Connected team data is retained only for the period your team selects. Contact your team administrator to request deletion.</p>':'<p>Diff Gate records review evidence. Your team remains responsible for code, security findings, and merge decisions.</p><p>Paid team access is sold by Sociobot, the merchant of record. A revoked license removes paid access.</p><p>Use the service only with repositories you are allowed to review.</p>'}</article>`, `${privacy?'Privacy':'Terms'} — Diff Gate`, `${privacy?'Privacy':'Terms'} — Diff Gate`); }
function notFound(){shell(`<section class="not-found"><p class="eyebrow">404</p><h1 tabindex="-1">This review desk is empty</h1><p>That page does not exist. Return to the packet list to continue reviewing.</p><button class="primary" id="go-home">Go to Diff Gate</button></section>`,'Not found — Diff Gate','Not found — Diff Gate');}
function render(){ const path=location.pathname; if(path==='/')landing(); else if(path==='/demo')demoPage(); else if(path==='/privacy')legal('privacy'); else if(path==='/terms')legal('terms'); else notFound(); }
function createBlank(){ draft={title:'Untitled change',owner:'Add responsible owner',source:'New review packet',changed:[],checks:[{label:'Changed contract',detail:'Describe the public behavior that changed.',state:'missing'},{label:'Test evidence',detail:'Add the command and result before approval.',state:'missing'}]}; render(); }
function saveLicense(){const e=document.querySelector<HTMLInputElement>('#license')!;const note=document.querySelector('#license-note')!; if(!e.value.trim()){note.textContent='Paste a license token, then restore access.';return;} localStorage.setItem('sb_license:agent-diff-gate',e.value.trim());note.textContent='License stored on this device. It will be checked when connected.';}
function bind(){ document.querySelectorAll<HTMLElement>('[data-nav]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();nav((a as HTMLAnchorElement).pathname)})); document.querySelector('#hero-demo')?.addEventListener('click',()=>{demo=true;draft=structuredClone(sample);nav('/demo')}); document.querySelector('#load-sample')?.addEventListener('click',()=>{demo=true;draft=structuredClone(sample);render()}); document.querySelector('#make-packet')?.addEventListener('click',createBlank); document.querySelector('#reset-demo')?.addEventListener('click',()=>{draft=structuredClone(sample);sessionStorage.removeItem('demo:diff-gate');render()}); document.querySelector('#start-real')?.addEventListener('click',()=>{demo=false;draft=null;nav('/')}); document.querySelector('#go-home')?.addEventListener('click',()=>nav('/')); document.querySelector('#save-license')?.addEventListener('click',saveLicense); document.querySelectorAll<HTMLButtonElement>('[data-resolve]').forEach(b=>b.addEventListener('click',()=>{if(!draft)return;draft.checks[Number(b.dataset.resolve)].state='done';render()})); document.querySelector('#approve-packet')?.addEventListener('click',()=>alert('Approval recorded in this review packet. Connect your team to retain approval history.')); document.querySelector('#export-packet')?.addEventListener('click',()=>{if(!draft)return;const blob=new Blob([JSON.stringify(draft,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='diff-gate-packet.json';a.click();URL.revokeObjectURL(a.href);}); }
window.addEventListener('popstate',render); window.addEventListener('online',()=>{offline=false;render()}); window.addEventListener('offline',()=>{offline=true;render()});
const license=new URLSearchParams(location.search).get('license'); if(license){localStorage.setItem('sb_license:agent-diff-gate',license);history.replaceState({},'',location.pathname);}
render();
